// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5J01lJu4rIuxMqyKRwWmNK6gqZw0hirA',
    appId: '1:185829547225:web:6bcadf7f539b0331e732c8',
    messagingSenderId: '185829547225',
    projectId: 'instadamm-aba78',
    authDomain: 'instadamm-aba78.firebaseapp.com',
    storageBucket: 'instadamm-aba78.firebasestorage.app',
    measurementId: 'G-WG18LRGTG4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD71Vi0J67-do_Pdn0FV5unBB7yqSc-zN0',
    appId: '1:185829547225:android:dd614650dd8568aee732c8',
    messagingSenderId: '185829547225',
    projectId: 'instadamm-aba78',
    storageBucket: 'instadamm-aba78.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYzg6ovAp1PcXzQ5PXhyugdV6intRVovQ',
    appId: '1:185829547225:ios:2fb40ed6dc496dc2e732c8',
    messagingSenderId: '185829547225',
    projectId: 'instadamm-aba78',
    storageBucket: 'instadamm-aba78.firebasestorage.app',
    iosBundleId: 'com.example.instadam',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYzg6ovAp1PcXzQ5PXhyugdV6intRVovQ',
    appId: '1:185829547225:ios:2fb40ed6dc496dc2e732c8',
    messagingSenderId: '185829547225',
    projectId: 'instadamm-aba78',
    storageBucket: 'instadamm-aba78.firebasestorage.app',
    iosBundleId: 'com.example.instadam',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5J01lJu4rIuxMqyKRwWmNK6gqZw0hirA',
    appId: '1:185829547225:web:29dc6cf1fe6e1547e732c8',
    messagingSenderId: '185829547225',
    projectId: 'instadamm-aba78',
    authDomain: 'instadamm-aba78.firebaseapp.com',
    storageBucket: 'instadamm-aba78.firebasestorage.app',
    measurementId: 'G-4MBWHN305P',
  );
}
